steps:
  # build
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-west2-docker.pkg.dev/${PROJECT_ID}/circleci-gcp/test-image:tag1",
        ".",
      ]
  # push to artifact
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-west2-docker.pkg.dev/${PROJECT_ID}/circleci-gcp/test-image:tag1",
      ]
  # deploy by cloud run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "circleci-test-deploy"
      - "--image"
      - "us-west2-docker.pkg.dev/${PROJECT_ID}/circleci-gcp/test-image:tag1"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
images:
  - "us-west2-docker.pkg.dev/circle-ci-test-368401/circleci-gcp/test-image:tag1"
